'use client';

import { useEffect, useState } from 'react';
import { api } from '../../../../../lib/api';

type SymbolDetail = { id: string; repository_id: string; file_id: string; name: string; qualified_name: string; type: string; language?: string | null; start_line: number; end_line: number; signature?: string | null; source_text?: string | null };
type Neighbor = { symbol: SymbolDetail; edge: { type?: string; confidence?: number | string | null; line?: number | null } };
type Citation = { repository: string; file_id: string; path: string; start_line: number; end_line: number; indexed_commit_sha?: string | null };
type Documentation = { markdown: string; citations: Citation[]; scope: { indexed_commit_sha?: string | null } };

function confidencePercent(value: Neighbor['edge']['confidence']) { const number = typeof value === 'number' ? value : typeof value === 'string' ? Number(value) : NaN; return Number.isFinite(number) ? Math.round(Math.max(0, Math.min(100, number <= 1 ? number * 100 : number))) : null; }

export default function SymbolPage({ params }: { params: Promise<{ repositoryId: string; symbolId: string }> }) {
  const [detail, setDetail] = useState<SymbolDetail | null>(null); const [callers, setCallers] = useState<Neighbor[]>([]); const [callees, setCallees] = useState<Neighbor[]>([]); const [documentation, setDocumentation] = useState<Documentation | null>(null); const [loadingDocumentation, setLoadingDocumentation] = useState(false); const [error, setError] = useState('');
  useEffect(() => { let active = true; async function load() { try { const { repositoryId, symbolId } = await params; const base = `/repositories/${encodeURIComponent(repositoryId)}/symbols/${encodeURIComponent(symbolId)}`; const [symbol, callerResponse, calleeResponse] = await Promise.all([api<SymbolDetail>(base), api<{ callers?: Neighbor[] }>(`${base}/callers`), api<{ callees?: Neighbor[] }>(`${base}/callees`)]); if (!active) return; setDetail(symbol); setCallers(callerResponse.callers ?? []); setCallees(calleeResponse.callees ?? []); } catch (cause) { if (active) setError(cause instanceof Error ? cause.message : 'Unable to load symbol details.'); } } void load(); return () => { active = false; }; }, [params]);
  async function generateDocumentation() { if (!detail) return; setLoadingDocumentation(true); setError(''); try { setDocumentation(await api<Documentation>('/documentation/generate', { method: 'POST', body: JSON.stringify({ repository_id: detail.repository_id, symbol_id: detail.id }) })); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to generate documentation.'); } finally { setLoadingDocumentation(false); } }
  if (error && !detail) return <><h2>Symbol</h2><div className="graph-message graph-error" role="alert">{error}</div></>;
  if (!detail) return <div className="graph-state" role="status">Loading symbol details…</div>;
  const sourceUrl = `/files/${encodeURIComponent(detail.file_id)}#L${detail.start_line}`; const graphUrl = `/graph?repository=${encodeURIComponent(detail.repository_id)}&symbol=${encodeURIComponent(detail.id)}`;
  const list = (title: string, items: Neighbor[]) => <section className="card symbol-neighbors"><h3>{title}</h3>{items.length === 0 ? <p className="muted">None found.</p> : <ul>{items.map(({ symbol, edge }) => <li key={`${symbol.id}-${edge.line ?? ''}`}><a href={`/repositories/${encodeURIComponent(detail.repository_id)}/symbols/${encodeURIComponent(symbol.id)}`}>{symbol.qualified_name || symbol.name}</a><span className="muted"> · {edge.type ?? 'related'}{edge.line ? ` at line ${edge.line}` : ''}{confidencePercent(edge.confidence) !== null ? ` · ${confidencePercent(edge.confidence)}% confidence` : ''}</span></li>)}</ul>}</section>;
  return <><div className="page-heading"><div><h2>{detail.qualified_name || detail.name}</h2><p className="muted">{detail.type} · {detail.language ?? 'unknown language'} · lines {detail.start_line}–{detail.end_line}</p></div></div><div className="repository-actions"><a href={sourceUrl}>Open source →</a><a href={graphUrl}>Open graph →</a><button type="button" onClick={generateDocumentation} disabled={loadingDocumentation}>{loadingDocumentation ? 'Generating…' : 'Generate documentation'}</button></div>{error && <div className="graph-message graph-error" role="alert">{error}</div>}{detail.signature && <section className="card symbol-section"><h3>Signature</h3><pre>{detail.signature}</pre></section>}<section className="card symbol-section"><h3>Source</h3><pre>{detail.source_text || 'Source text is unavailable for this symbol.'}</pre></section><div className="symbol-neighbor-grid">{list('Callers', callers)}{list('Callees', callees)}</div>{documentation && <section className="card symbol-section"><h3>Generated documentation</h3><p className="muted">Commit {documentation.scope.indexed_commit_sha?.slice(0, 12) ?? 'unknown'} · generated from indexed direct evidence.</p><pre>{documentation.markdown}</pre><h4>Sources</h4>{documentation.citations.map((citation, index) => <a className="citation" key={index} href={`/files/${citation.file_id}#L${citation.start_line}`}>{citation.repository}/{citation.path}:{citation.start_line}-{citation.end_line}{citation.indexed_commit_sha ? ` · ${citation.indexed_commit_sha.slice(0, 12)}` : ''}</a>)}</section>}</>;
}
