import uuid
from datetime import datetime
from sqlalchemy import String, Text, Integer, DateTime, ForeignKey, JSON, Index, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column
from pgvector.sqlalchemy import Vector
from app.db import Base
def uid(): return str(uuid.uuid4())
def now(): return datetime.utcnow()
class Repository(Base):
 __tablename__='repositories'
 id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); name:Mapped[str]=mapped_column(String(255),index=True); clone_url:Mapped[str]=mapped_column(Text); local_path:Mapped[str|None]=mapped_column(Text,nullable=True); provider:Mapped[str]=mapped_column(String(30),default='git'); default_branch:Mapped[str|None]=mapped_column(String(255),nullable=True); indexed_branch:Mapped[str|None]=mapped_column(String(255),nullable=True); indexed_commit_sha:Mapped[str|None]=mapped_column(String(64),nullable=True); latest_detected_commit_sha:Mapped[str|None]=mapped_column(String(64),nullable=True); indexing_status:Mapped[str]=mapped_column(String(20),default='pending',index=True); indexing_progress:Mapped[dict]=mapped_column(JSON,default=dict); error_message:Mapped[str|None]=mapped_column(Text,nullable=True); last_indexed_at:Mapped[datetime|None]=mapped_column(DateTime,nullable=True); last_sync_at:Mapped[datetime|None]=mapped_column(DateTime,nullable=True); created_at:Mapped[datetime]=mapped_column(DateTime,default=now); updated_at:Mapped[datetime]=mapped_column(DateTime,default=now,onupdate=now)
class Workspace(Base):
 __tablename__='workspaces'
 id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); name:Mapped[str]=mapped_column(String(255),index=True); description:Mapped[str|None]=mapped_column(Text,nullable=True); created_at:Mapped[datetime]=mapped_column(DateTime,default=now); updated_at:Mapped[datetime]=mapped_column(DateTime,default=now,onupdate=now)
class WorkspaceRepository(Base):
 __tablename__='workspace_repositories'; __table_args__=(UniqueConstraint('repository_id',name='uq_workspace_repositories_repository_id'),)
 workspace_id:Mapped[str]=mapped_column(ForeignKey('workspaces.id',ondelete='CASCADE'),primary_key=True); repository_id:Mapped[str]=mapped_column(ForeignKey('repositories.id',ondelete='CASCADE'),primary_key=True); created_at:Mapped[datetime]=mapped_column(DateTime,default=now)
class File(Base):
 __tablename__='files'; __table_args__=(Index('ix_files_repo_path','repository_id','path',unique=True),)
 id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); repository_id:Mapped[str]=mapped_column(ForeignKey('repositories.id',ondelete='CASCADE'),index=True); path:Mapped[str]=mapped_column(Text); language:Mapped[str|None]=mapped_column(String(50),index=True); content:Mapped[str]=mapped_column(Text); content_hash:Mapped[str]=mapped_column(String(64),index=True); size_bytes:Mapped[int]=mapped_column(Integer); indexed_commit_sha:Mapped[str]=mapped_column(String(64)); created_at:Mapped[datetime]=mapped_column(DateTime,default=now); updated_at:Mapped[datetime]=mapped_column(DateTime,default=now,onupdate=now)
class Symbol(Base):
 __tablename__='symbols'; __table_args__=(Index('ix_symbols_repo_name','repository_id','name'),)
 id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); repository_id:Mapped[str]=mapped_column(ForeignKey('repositories.id',ondelete='CASCADE'),index=True); file_id:Mapped[str]=mapped_column(ForeignKey('files.id',ondelete='CASCADE'),index=True); name:Mapped[str]=mapped_column(String(255),index=True); qualified_name:Mapped[str]=mapped_column(String(512),index=True); symbol_type:Mapped[str]=mapped_column(String(40)); language:Mapped[str|None]=mapped_column(String(50)); start_line:Mapped[int]=mapped_column(Integer); end_line:Mapped[int]=mapped_column(Integer); start_byte:Mapped[int]=mapped_column(Integer); end_byte:Mapped[int]=mapped_column(Integer); parent_symbol_id:Mapped[str|None]=mapped_column(ForeignKey('symbols.id'),nullable=True); source_text:Mapped[str]=mapped_column(Text); signature:Mapped[str|None]=mapped_column(Text,nullable=True)
class CodeChunk(Base):
 __tablename__='code_chunks'; __table_args__=(Index('ix_chunks_repo_file','repository_id','file_id'),)
 id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); repository_id:Mapped[str]=mapped_column(ForeignKey('repositories.id',ondelete='CASCADE'),index=True); file_id:Mapped[str]=mapped_column(ForeignKey('files.id',ondelete='CASCADE'),index=True); symbol_id:Mapped[str|None]=mapped_column(ForeignKey('symbols.id',ondelete='SET NULL'),nullable=True); language:Mapped[str|None]=mapped_column(String(50)); chunk_type:Mapped[str]=mapped_column(String(30)); symbol_name:Mapped[str|None]=mapped_column(String(255)); qualified_symbol_name:Mapped[str|None]=mapped_column(String(512)); start_line:Mapped[int]=mapped_column(Integer); end_line:Mapped[int]=mapped_column(Integer); source_text:Mapped[str]=mapped_column(Text); content_hash:Mapped[str]=mapped_column(String(64),index=True); indexed_commit_sha:Mapped[str]=mapped_column(String(64)); embedding:Mapped[list[float]|None]=mapped_column(Vector(),nullable=True); embedding_model:Mapped[str|None]=mapped_column(String(255),nullable=True)
class SymbolEdge(Base):
 __tablename__='symbol_edges'; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); repository_id:Mapped[str]=mapped_column(ForeignKey('repositories.id',ondelete='CASCADE'),index=True); source_symbol_id:Mapped[str|None]=mapped_column(ForeignKey('symbols.id'),nullable=True); target_symbol_id:Mapped[str|None]=mapped_column(ForeignKey('symbols.id'),nullable=True); target_name:Mapped[str]=mapped_column(String(512),index=True); relationship_type:Mapped[str]=mapped_column(String(30)); source_file_id:Mapped[str]=mapped_column(ForeignKey('files.id',ondelete='CASCADE')); line_number:Mapped[int]=mapped_column(Integer); confidence:Mapped[int]=mapped_column(Integer,default=50)
class IndexingJob(Base):
 __tablename__='indexing_jobs'; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); repository_id:Mapped[str]=mapped_column(ForeignKey('repositories.id',ondelete='CASCADE'),index=True); kind:Mapped[str]=mapped_column(String(30)); status:Mapped[str]=mapped_column(String(20),default='pending'); progress:Mapped[dict]=mapped_column(JSON,default=dict); error_message:Mapped[str|None]=mapped_column(Text,nullable=True); created_at:Mapped[datetime]=mapped_column(DateTime,default=now); started_at:Mapped[datetime|None]=mapped_column(DateTime,nullable=True); finished_at:Mapped[datetime|None]=mapped_column(DateTime,nullable=True)
class Conversation(Base):
 __tablename__='conversations'; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); repository_id:Mapped[str|None]=mapped_column(ForeignKey('repositories.id'),nullable=True); title:Mapped[str]=mapped_column(String(255),default='New conversation'); created_at:Mapped[datetime]=mapped_column(DateTime,default=now)
class Message(Base):
 __tablename__='messages'; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); conversation_id:Mapped[str]=mapped_column(ForeignKey('conversations.id',ondelete='CASCADE'),index=True); role:Mapped[str]=mapped_column(String(20)); content:Mapped[str]=mapped_column(Text); citations:Mapped[list]=mapped_column(JSON,default=list); created_at:Mapped[datetime]=mapped_column(DateTime,default=now)
